#!/bin/bash


echo "* Running set app permissions..."
echo "* 执行设置 APP 权限中..."

chown root:wheel /Applications/Sileo Demo.app/Sileo Demo
chmod +s /Applications/Sileo Demo.app/Sileo Demo

echo "* Running set app permissions... Done."
echo "* 执行设置 APP 权限中... 完成"

echo "* Running uicache..."
echo "* 执行刷新图标缓存中..."

su mobile -c uicache

echo "* Running uicache... Done."
echo "* 执行刷新图标缓存中... 完成"

echo "* Thanks for using My Repo Tweaks.Aaron wishes every jailbreak player a good time！"
echo "* 感谢使用本源插件.Aaron祝每个越狱玩家玩得开心！"

finish reopen

exit 0;