#!/bin/bash
dir=$(dirname "$0")
chown root:wheel /Applications/CheatEngineIO.app/ce_daemon
chmod 6755 /Applications/CheatEngineIO.app/ce_daemon

cp /Applications/CheatEngineIO.app/aqua.ce.*.plist /Library/LaunchDaemons/
launchctl load -w /Library/LaunchDaemons/aqua.ce.daemon.plist

if [[ ! -d /var/mobile/Library/CheatEngineIO ]]; then
    mkdir /var/mobile/Library/CheatEngineIO
    chown mobile /var/mobile/Library/CheatEngineIO
fi

uicache --all

exit 0
