#!/bin/bash
echo "==========================="
echo "正在恢复原字体，请耐心等候…"
firmware=$(sw_vers -productVersion)
if  [[ $firmware == 11.* ]]; then
    cp -a /var/mobile/Documents/MFFont/FontBackups/IOS11/* /System/Library/Fonts/
    rm -rf /var/mobile/Documents/Fonts
	rm -rf /var/mobile/Documents/MFFont
fi

firmware=$(sw_vers -productVersion)
if  [[ $firmware == 12.* ]]; then
    cp -a /var/mobile/Documents/MFFont/FontBackups/IOS12/* /System/Library/Fonts/
	rm -rf /var/mobile/Documents/Fonts
    rm -rf /var/mobile/Documents/MFFont
fi

firmware=$(sw_vers -productVersion)
if  [[ $firmware == 13.* ]]; then
    cp -a /var/mobile/Documents/MFFont/FontBackups/IOS13/* /System/Library/Fonts/
	rm -rf /var/mobile/Documents/Fonts
    rm -rf /var/mobile/Documents/MFFont
fi

echo "┄┄┄┄┄┄┄┄┄┄┄┄┄┄"
echo "正在清理缓存…"
rm -rf /var/mobile/Library/Caches/com.apple.UIStatusBar
rm -rf /var/mobile/Library/Caches/com.apple.keyboards
rm -fr /var/root/Library/Caches/com.apple.keyboards
rm -fr /var/mobile/Library/Caches/TelephonyUI*
rm -fr /var/mobile/Containers/Data/Application/*/Library/Caches/TelephonyUI*
uicache
echo "清理成功"
echo ""
echo "==================================="
echo ">>>>>>>>>>>Aaron Repo™<<<<<<<<<"
echo ">>http://sileo.vip<<"
echo ">>>>>>>感谢使用Aaron源软件<<<<<<<"
echo ">>字体恢复成功，注销手机即可生效!<<"
echo "==================================="
