#!/bin/bash
firmware=$(sw_vers -productVersion) 
echo "设备系统版本：iOS $firmware"
echo "============================"
echo "安装字体前请详细阅读插件说明"
echo "----------------------------"
echo "正在备份原字体，请耐心等待…"
echo "过程中切勿退出Cydia后台...."
#IOS11:
#>>>>>>备份字体<<<<<<
firmware=$(sw_vers -productVersion)
if  [[ $firmware == 11.* ]]; then
     mkdir /var/mobile/Documents/MFFont/FontBackups/IOS11
     cp -a /System/Library/Fonts/* /var/mobile/Documents/MFFont/FontBackups/IOS11/
fi

#IOS12:
#>>>>>>备份字体<<<<<<
firmware=$(sw_vers -productVersion)
if  [[ $firmware == 12.* ]]; then
     mkdir /var/mobile/Documents/MFFont/FontBackups/IOS12
     cp -a /System/Library/Fonts/* /var/mobile/Documents/MFFont/FontBackups/IOS12/
fi


#IOS13:
#>>>>>>备份字体<<<<<<
firmware=$(sw_vers -productVersion)
if  [[ $firmware == 13.* ]]; then
     mkdir /var/mobile/Documents/MFFont/FontBackups/IOS13
     cp -a /System/Library/Fonts/* /var/mobile/Documents/MFFont/FontBackups/IOS13/
fi
echo "备份原字体成功!"
echo "----------------------------"
echo "开始替换字体…"
echo ""
#IOS11:
#>>>>>>更换字体<<<<<<
firmware=$(sw_vers -productVersion)
if  [[ $firmware == 11.* ]]; then
     mv /var/mobile/Documents/Fonts/LanguageSupport/* /System/Library/Fonts/LanguageSupport/
     mv /var/mobile/Documents/Fonts/iOS12/Core/* /System/Library/Fonts/Core/
     mv /var/mobile/Documents/Fonts/iOS12/CoreAddition/* /System/Library/Fonts/CoreAddition/
     mv /var/mobile/Documents/Fonts/iOS12/CoreUI/* /System/Library/Fonts/CoreUI/
fi

#IOS12:
#>>>>>>更换字体<<<<<<
firmware=$(sw_vers -productVersion)
if  [[ $firmware == 12.* ]]; then
     mv /var/mobile/Documents/Fonts/LanguageSupport/* /System/Library/Fonts/LanguageSupport/
     mv /var/mobile/Documents/Fonts/iOS12/Core/* /System/Library/Fonts/Core/
     mv /var/mobile/Documents/Fonts/iOS12/CoreAddition/* /System/Library/Fonts/CoreAddition/
     mv /var/mobile/Documents/Fonts/iOS12/CoreUI/* /System/Library/Fonts/CoreUI/
fi


#IOS13:
#>>>>>>更换字体<<<<<<
firmware=$(sw_vers -productVersion)
if  [[ $firmware == 13.* ]]; then
     mv /var/mobile/Documents/Fonts/LanguageSupport/* /System/Library/Fonts/LanguageSupport/
     mv /var/mobile/Documents/Fonts/iOS13/Core/* /System/Library/Fonts/Core/
     mv /var/mobile/Documents/Fonts/iOS13/CoreAddition/* /System/Library/Fonts/CoreAddition/
     mv /var/mobile/Documents/Fonts/iOS13/CoreUI/* /System/Library/Fonts/CoreUI/
fi

echo "----------------------------"
echo "正在清理缓存…"
echo ""
rm -rf /var/mobile/Library/Caches/com.apple.UIStatusBar
rm -rf /var/mobile/Library/Caches/com.apple.keyboards
rm -fr /var/root/Library/Caches/com.apple.keyboards
rm -fr /var/mobile/Library/Caches/TelephonyUI*
rm -fr /var/mobile/Containers/Data/Application/*/Library/Caches/TelephonyUI*
uicache
echo "清理成功"
echo ""
echo "==================================="
echo ">>>>>>>>>>>Aaron Repo™<<<<<<<<<"
echo ">>http://sileo.vip<<"
echo ">>>>>>>感谢使用Aaron源软件<<<<<<<"
echo ">>字体替换成功，注销手机即可生效!<<"
echo "==================================="
